#!/usr/bin/env ansible-playbook
---
- name: generate formulae
  hosts: localhost
  tasks:
    - name: librewolf
      include_tasks: tasks/codeberg-formula.yml
      vars:
        formula:
          release_api: "https://codeberg.org/api/v1/repos/librewolf/bsys6/releases/latest"
          template_src: "Casks/l/librewolf.rb.j2"

    - name: qbittorrent
      include_tasks: tasks/qbittorrent.yml
      vars:
        formula:
          release_api: "https://api.github.com/repos/qBittorrent/qBittorrent/releases/latest"
          template_src: "Casks/q/qbittorrent.rb.j2"

    - name: xmoto
      include_tasks: tasks/xmoto.yml
      vars:
        formula:
          release_api: "https://api.github.com/repos/xmoto/xmoto/releases/latest"
          template_src: "Casks/x/xmoto.rb.j2"

    - name: fedora-media-writer
      include_tasks: tasks/fedora-media-writer.yml
      vars:
        formula:
          release_api: "https://api.github.com/repos/FedoraQt/MediaWriter/releases/latest"
          template_src: "Casks/f/fedora-media-writer.rb.j2"
