name: PR Check - Install LibreWolf

on:
  pull_request:
    branches:
      - master

jobs:
  install-librewolf:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: brew tap
        run: brew tap akdev1l/apps

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: "$(brew --repository/Library/Taps/akdev1l/homebrew-apps"

      - name: Install LibreWolf
        run: brew install --verbose librewolf

      - name: Verify installation
        run: librewolf --version
